### ISSUE TITLE
`readlink` does not have a `-f` option on macOS

### ISSUE THREAD

**Issue by martijnbleeker** [pietvanzoen/git-get#2]
The install script uses `readlink -f`. However, the version that ships with macOS does not support that flag.
The way around it, for me, was to `brew install coreutils` and change the call to `greadlink`, which worked. But it might be an unwanted dependency to the script.

**Comment by martijnbleeker** [comment]
I did find a possible answer on [stackexchange](https://apple.stackexchange.com/a/14669), but that will very likely break compatibility with linux-y systems.

**Comment by pietvanzoen** [comment]
@martijnbleeker mind pulling this and validating the fix? https://github.com/pietvanzoen/git-get/pull/3

**Comment by martijnbleeker** [comment]
Looks like it's working. 👍
